Amended tests to use gtest.

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -14,25 +14,52 @@ env:
   BUILD_TYPE: RelWithDebInfo
 
 jobs:
+  gtest:
+    uses: kingkybel/CMakeCommon/.github/workflows/dependency-cache.yml@main
+    with:
+      dependency-name: gtest
+      dependency-version: 1.17.0
+
   build:
     # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
     # You can convert this to a matrix build if you need cross-platform coverage.
     # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
     runs-on: ubuntu-latest
+    needs:
+      - gtest
 
     steps:
     - uses: actions/checkout@v4
       with:
         submodules: recursive
 
+    - name: Restore gtest cache
+      uses: actions/cache@v4
+      with:
+        path: build/dkyb-cache
+        key: deps-gtest-1.17.0-${{ hashFiles('cmake/**') }}
+        restore-keys: |
+          deps-gtest-1.17.0-
+          deps-gtest-
+
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
+      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDKYB_DEPENDENCY_CACHE_ROOT=${{github.workspace}}/build/dkyb-cache
 
     - name: Build
       # Build your program with the given configuration
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+
+    - name: Test
+      # Execute tests defined by the CMake configuration.
+      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+      run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}} --output-on-failure
+
+    - name: Test
+      # Execute tests defined by the CMake configuration.
+      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+      run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}} --output-on-failure
 
 
   coverage:
@@ -46,6 +73,71 @@ jobs:
     - uses: actions/checkout@v4
       with:
         submodules: recursive
+
+    - name: Cache gtest
+      uses: actions/cache@v4
+      id: cache-gtest
+      with:
+        path: ~/gtest
+        key: ${{ runner.os }}-gtest-latest
+
+    - name: Install gtest
+      env:
+        CACHE_HIT: ${{steps.cache-gtest.outputs.cache-hit}}
+      run: |
+        if [[ "$CACHE_HIT" == 'true' ]]; then
+          cd ~/gtest
+          sudo cp lib/*.a /usr/lib
+          sudo cp -R ~/gtest/* /usr
+        else
+          git clone https://github.com/google/googletest.git
+          cd googletest
+          mkdir build
+          cd build
+          cmake ..
+          cmake --build .
+          mkdir -p ~/gtest
+          cmake --install . --prefix ~/gtest
+          cd ~/gtest
+          sudo cp lib/*.a /usr/lib
+          sudo cp -R ~/gtest/* /usr
+        fi
+
+    - name: Cache boost
+      uses: actions/cache@v4
+      id: cache-boost
+      with:
+        path: ~/boost
+        key: ${{ runner.os }}-boost-1.90.0
+
+    - name: Install Boost
+      env:
+        CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
+      run: |
+        if [[ "$CACHE_HIT" == 'true' ]]; then
+          sudo cp --force --recursive ~/boost/* /usr
+        else
+          BOOST_MAJOR=1
+          BOOST_MID=90
+          BOOST_MINOR=0
+          BOOST_VER=${BOOST_MAJOR}_${BOOST_MID}_${BOOST_MINOR}
+          BOOST_VER_DOT=${BOOST_MAJOR}.${BOOST_MID}.${BOOST_MINOR}
+          wget --quiet -O boost_${BOOST_VER}.tar.gz https://sourceforge.net/projects/boost/files/boost/${BOOST_VER_DOT}/boost_${BOOST_VER}.tar.gz/download
+          tar -xf boost_${BOOST_VER}.tar.gz
+          cd boost_${BOOST_VER}
+          mkdir -p ~/boost
+          ./bootstrap.sh --prefix=/home/runner/boost
+          ./b2 install -j $(nproc) --quiet || { echo "Boost build failed"; exit 1; }
+          sudo cp --force --recursive ~/boost/* /usr
+        fi
+
+    - name: Install TypeTraits
+      run: |
+        mkdir -p ${{github.workspace}}/TypeTraits/build
+        cd ${{github.workspace}}/TypeTraits/build
+        cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/usr -S ..
+        cmake --build . --parallel $(nproc)
+        sudo cmake --install .
     - name: Install lcov
       run: |
         sudo apt-get update
@@ -137,6 +229,71 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y build-essential cmake ninja-build curl unzip
+
+      - name: Cache gtest
+        uses: actions/cache@v4
+        id: cache-gtest
+        with:
+          path: ~/gtest
+          key: ${{ runner.os }}-gtest-latest
+
+      - name: Install gtest
+        env:
+          CACHE_HIT: ${{steps.cache-gtest.outputs.cache-hit}}
+        run: |
+          if [[ "$CACHE_HIT" == 'true' ]]; then
+            cd ~/gtest
+            sudo cp lib/*.a /usr/lib
+            sudo cp -R ~/gtest/* /usr
+          else
+            git clone https://github.com/google/googletest.git
+            cd googletest
+            mkdir build
+            cd build
+            cmake ..
+            cmake --build .
+            mkdir -p ~/gtest
+            cmake --install . --prefix ~/gtest
+            cd ~/gtest
+            sudo cp lib/*.a /usr/lib
+            sudo cp -R ~/gtest/* /usr
+          fi
+
+      - name: Cache boost
+        uses: actions/cache@v4
+        id: cache-boost
+        with:
+          path: ~/boost
+          key: ${{ runner.os }}-boost-1.90.0
+
+      - name: Install Boost
+        env:
+          CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
+        run: |
+          if [[ "$CACHE_HIT" == 'true' ]]; then
+            sudo cp --force --recursive ~/boost/* /usr
+          else
+            BOOST_MAJOR=1
+            BOOST_MID=90
+            BOOST_MINOR=0
+            BOOST_VER=${BOOST_MAJOR}_${BOOST_MID}_${BOOST_MINOR}
+            BOOST_VER_DOT=${BOOST_MAJOR}.${BOOST_MID}.${BOOST_MINOR}
+            wget --quiet -O boost_${BOOST_VER}.tar.gz https://sourceforge.net/projects/boost/files/boost/${BOOST_VER_DOT}/boost_${BOOST_VER}.tar.gz/download
+            tar -xf boost_${BOOST_VER}.tar.gz
+            cd boost_${BOOST_VER}
+            mkdir -p ~/boost
+            ./bootstrap.sh --prefix=/home/runner/boost
+            ./b2 install -j $(nproc) --quiet || { echo "Boost build failed"; exit 1; }
+            sudo cp --force --recursive ~/boost/* /usr
+          fi
+
+      - name: Install TypeTraits
+        run: |
+          mkdir -p ${{github.workspace}}/TypeTraits/build
+          cd ${{github.workspace}}/TypeTraits/build
+          cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/usr -S ..
+          cmake --build . --parallel $(nproc)
+          sudo cmake --install .
 
       - name: Install Sonar build-wrapper
         run: |
